---
title: "Risk Assessment Dashboard"
author: "Mohammed Rahman"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---


```{r}
tags$style(type="text/css",
  ".shiny-output-error { visibility: hidden; }",
  ".shiny-output-error:before { visibility: hidden; }"
)
library(data.table)
library(tidyverse)
library(gtsummary)
library(shiny)
library(skimr)
library(inspectdf)
library(editData)
library(tidyselect)
library(lubridate)
library(gmodels)
library(htmlTable)
library(summarytools)
library(ggplot2)
library(ggpubr)
library(ggsci)
library(plotly)
theme_set(theme_pubr())
ex_data <- fread("example_data.csv")
```

Importing Data
=======================================================================

Importing Data

```{r}
sidebarPanel(
selectInput("importer", "Data Import Method", c("R Environment", "Upload CSV")),
conditionalPanel(
  condition = "input.importer == 'Upload CSV'",
  fileInput("file1", "Choose CSV File",
       accept = c(
         "text/csv",
         "text/comma-separated-values,text/plain",
         ".csv"))),
       conditionalPanel(
         condition = "input.importer == 'R Environment'",
         textInput("text", "Enter Dataset Name in Global Environment", value = "ex_data")
       )
       )

#checkboxInput("importer", "Click to Upload") 
importing <- reactive(if(input$importer == "R Environment"){
      assign("dataset", get(input$text))
    } else{
    dataset <- fread(input$file1$datapath)
    })
```

<!-- Row -->
<!-- ------------------------------------- -->

<!-- ```{r} -->
<!-- renderUI({ -->
<!--     dataset <- importing() -->
<!-- fluidRow( -->
<!--   selectInput3("var_1", "_Select Variable", c(" ", names(dataset)), width = 300), -->
<!--     selectInput3("type_1", "Select New Type", c("Numeric", "Character", "Date", "Factor"), width = 300) -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->

<!-- Row -->
<!-- ------------------------------------- -->

<!-- ```{r} -->
<!-- renderUI({ -->
<!--     dataset <- importing() -->
<!-- fluidRow( -->
<!--   selectInput3("var_2", "_Select Variable", c(" ", names(dataset)), width = 300), -->
<!--     selectInput3("type_2", "Select New Type", c("Numeric", "Character", "Date", "Factor"), width = 300) -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->

<!-- Row -->
<!-- ------------------------------------- -->

<!-- ```{r} -->

<!-- renderUI({ -->
<!--     dataset <- importing() -->
<!-- fluidRow( -->
<!--   selectInput3("var_3", "_Select Variable", c(" ", names(dataset)), width = 300), -->
<!--     selectInput3("type_3", "Select New Type", c("Numeric", "Character", "Date", "Factor"), width = 300) -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->

<!-- Row -->
<!-- ------------------------------------- -->

<!-- ```{r} -->

<!-- renderUI({ -->
<!--     dataset <- importing() -->
<!-- fluidRow( -->
<!--   selectInput3("var_4", "_Select Variable", c(" ", names(dataset)), width = 300), -->
<!--     selectInput3("type_4", "Select New Type", c("Numeric", "Character", "Date", "Factor"), width = 300) -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->

<!-- Row -->
<!-- ------------------------------------- -->

<!-- ```{r} -->
<!-- renderUI({ -->
<!--     dataset <- importing() -->
<!-- fluidRow( -->
<!--   selectInput3("var_5", "_Select Variable", c(" ", names(dataset)), width = 300), -->
<!--     selectInput3("type_5", "Select New Type", c("Numeric", "Character", "Date", "Factor"), width = 300) -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->


Data
=======================================================================

```{r}
renderTable({
  dataset <- importing()
  dataset}, 
  striped = T,
  hover = T,
  bordered = T)
```

Summary
=======================================================================

<!-- Inputs {.sidebar} -->
<!-- ------------------------------------- -->

```{r Inputs for Summary Tab}
output$choose <- renderUI({
  dataset <- importing()
  selectizeInput(
    "selector",
    "Choose Variables",
    names(dataset),
    selected = names(dataset),
    multiple = T,
    width = 300
    )
  })

#Scatterplot Inputs
output$scatterx <- renderUI({
    dataset <- importing()
    vars <- dataset %>% select_if(is.numeric) %>% names()

  selectInput("scatterx", "Select X Variable", c(vars), width = 300)
})


output$scattery <- renderUI({
    dataset <- importing()
    vars <- dataset %>% select_if(is.numeric) %>% names()
  selectInput("scattery", "Select Y Variable", c(vars), width = 300)
})

output$scattersize <- renderUI({
    dataset <- importing()
    vars <- dataset %>% select_if(is.numeric) %>% names()
  selectInput("scattersize", "Select Sizing Variable", c(" ", vars), width = 300)
})

output$scattergroup <- renderUI({
    dataset <- importing()
    va <- dataset %>% select_if(is.character) %>% names()
    rs <- dataset %>% select_if(is.factor) %>% names()
    vars <- c(va,rs)
  selectInput("scattergroup", "Select Grouping Variable", c(" ", vars), width = 300)
})

#Barplot Inputs
output$barx <- renderUI({
    dataset <- importing()
    va <- dataset %>% select_if(is.character) %>% names()
    rs <- dataset %>% select_if(is.factor) %>% names()
    vars <- c(va,rs)

  selectInput("barx", "Select X Variable", c(vars), width = 300)
})

output$bargroup <- renderUI({
    dataset <- importing()
    va <- dataset %>% select_if(is.character) %>% names()
    rs <- dataset %>% select_if(is.factor) %>% names()
    vars <- c(va,rs)
  selectInput("bargroup", "Select Grouping Variable", c(" ", vars), width = 300)
})

output$boxx <- renderUI({
    dataset <- importing()
    va <- dataset %>% select_if(is.character) %>% names()
    rs <- dataset %>% select_if(is.factor) %>% names()
    vars <- c(va,rs)

  selectInput("boxx", "Select X Variable", c(vars), width = 300)
})

output$boxy <- renderUI({
    dataset <- importing()
    vars <- dataset %>% select_if(is.numeric) %>% names()
  selectInput("boxy", "Select Y Variable", c(vars), width = 300)
})

output$boxgroup <- renderUI({
    dataset <- importing()
    va <- dataset %>% select_if(is.character) %>% names()
    rs <- dataset %>% select_if(is.factor) %>% names()
    vars <- c(va,rs)
  selectInput("boxgroup", "Select Grouping Variable", c(" ", vars), width = 300)
})

#Cross Table

output$crossx <- renderUI({
    dataset <- importing()
    va <- dataset %>% select_if(is.character) %>% names()
    rs <- dataset %>% select_if(is.factor) %>% names()
    vars <- c(va,rs)

  selectInput("crossx", "Select X Variable", c(vars), width = 300)
})

output$crossy <- renderUI({
    dataset <- importing()
    va <- dataset %>% select_if(is.character) %>% names()
    rs <- dataset %>% select_if(is.factor) %>% names()
    vars <- c(va,rs)

  selectInput("crossy", "Select X Variable", c(vars), width = 300)
})
```

```{r side Panel}
#SideBar Panel
sidebarPanel(
  uiOutput("choose"),
  conditionalPanel(condition = "input.conditionedPanels == 'scatter'",
                   uiOutput("scatterx"),
                   uiOutput("scattery"),
                   uiOutput("scattersize"),
                   uiOutput("scattergroup")),
  conditionalPanel(condition = "input.conditionedPanels == 'bar'",
                   uiOutput("barx"),
                   uiOutput("bargroup")),
  conditionalPanel(condition = "input.conditionedPanels == 'box'",
                   uiOutput("boxx"),
                   uiOutput("boxy"),
                   uiOutput("boxgroup")),
  conditionalPanel(condition = "input.conditionedPanels == 'cross'",
                   uiOutput("crossx"),
                   uiOutput("crossy")),
  width = 2
)
```

```{r Main Panel}
#Main Panel
mainPanel(
  tabsetPanel(
    tabPanel("Summary",
             value = "summary",
             tableOutput("sumTable")),
    tabPanel("Scatterplot",
             value = "scatter",
             plotlyOutput("scatterPlot")),
    tabPanel("Barplot",
             value = "bar",
             plotlyOutput("barPlot")),
    tabPanel("Boxplot",
             value = "box",
             plotlyOutput("boxPlot")),
    tabPanel("Cross Table",
             value = "cross",
             verbatimTextOutput("crossTable")),
    id = "conditionedPanels"
    )
  )
```

```{r summary & corr}
output$sumTable <- renderTable({
  dataset <- importing()
  a <- as.vector(input$selector)
  b <- dataset[,names(dataset) %in% a]
  dataset <- dataset[,..b]
  data <- psych::describe(dataset %>% select_if(is.numeric))
  data %>% mutate(vars = row.names(data))
})

output$corr <- renderPlot({
  dataset <- importing()
  a <- as.vector(input$selector)
  b <- dataset[,names(dataset) %in% a]
  dataset <- dataset[,..b]
  data <- dataset %>% select_if(is.numeric)
  corr <- cor(data)
  corrplot::corrplot.mixed(corr)
},
width = 500,
height = 500)
```

```{r scatter}
output$scatterPlot <- renderPlotly({
  dataset <- importing()
  a <- as.vector(input$selector)
  b <- dataset[,names(dataset) %in% a]
  dataset <- dataset[,..b]

p <- ggplot(
    data = dataset, aes_string(x = input$scatterx, y = input$scattery)) +
    scale_fill_simpsons() +
    scale_color_simpsons()

if(input$scattergroup == " " & input$scattersize == " "){
  ggplotly(p + geom_point()) %>% layout(legend = list(orientation = "h", x = 0.4, y = -0.2))
} else if(input$scattergroup != " " & input$scattersize == " "){
  ggplotly(p + geom_point(aes_string(col = input$scattergroup))) %>%
      layout(legend = list(orientation = "h", x = 0.4, y = -0.2))
} else if(input$scattergroup == " " & input$scattersize != " "){
  ggplotly(p + geom_point(aes_string(size = input$scattersize))) %>%
      layout(legend = list(orientation = "h", x = 0.4, y = -0.2))
} else if(input$scattergroup != " " & input$scattersize != " "){
  ggplotly(p + geom_point(aes_string(col = input$scattergroup, size = input$scattersize))) %>%
      layout(legend = list(orientation = "h", x = 0.4, y = -0.2))
}
})
```

```{r boxPlot}
output$boxPlot <- renderPlotly({
dataset <- importing()

  a <- as.vector(input$selector)
  b <- dataset[,names(dataset) %in% a]
  dataset <- dataset[,..b]

  p <- ggplot(
    data = dataset, aes_string(x = input$boxx, y = input$boxy)) +
    scale_fill_simpsons() +
    scale_color_simpsons()

  if(input$boxgroup == " "){
  ggplotly(p + geom_boxplot(col = "slateblue3")) %>% layout(legend = list(orientation = "h", x = 0.4, y = -0.2))
  } else{
  ggplotly(
    p +
    geom_boxplot( aes_string(fill = input$boxgroup))) %>%
    layout(legend = list(orientation = "h", x = 0.4, y = -0.2)) %>%
    layout(boxmode = "group")
  }
})
```

```{r Barplot}
output$barPlot <- renderPlotly({
dataset <- importing()

  a <- as.vector(input$selector)
  b <- dataset[,names(dataset) %in% a]
  dataset <- dataset[,..b]
  va <- dataset %>% select_if(is.character) %>% names()
  rs <- dataset %>% select_if(is.factor) %>% names()
  vars <- c(va,rs)
  b <- dataset[,names(dataset) %in% vars]
  dataset <- dataset[,..b]
  p <- ggplot(
    data = dataset, aes_string(x = input$barx)) +
    scale_fill_simpsons()

  if(input$bargroup == " "){
  ggplotly(p + geom_bar(fill = "slateblue3") ) %>% layout(legend = list(orientation = "h", x = 0.4, y = -0.2))
  } else{
  ggplotly(
    p + geom_bar(aes_string(fill = input$bargroup)))%>%
      layout(legend = list(orientation = "h", x = 0.4, y = -0.2))
  }
})
```

```{r cross table}
output$crossTable <- renderPrint({
  dataset <- importing()
  a <- as.vector(input$selector)
  b <- dataset[,names(dataset) %in% a]
  dataset <- dataset[,..b] %>% as.data.frame()
  CrossTable(dataset[, input$crossx],
             dataset[, input$crossy],
             format="SPSS")
  # ftable(table(dataset[, input$cross_var1],
  #            dataset[, input$cross_var2]))
})
```

Survival Analysis
=======================================================================


Longitudinal Analysis
=======================================================================

Linear Regression
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------
  

Downloads
=======================================================================
